---
# Source: application-generator/templates/stage.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: management-argocd
  namespace: homelab-management
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: argocd
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/syoder89-homelab/homelab-management
      - name: targetBranch
        value: env/management/argocd
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
      - task:
          name: prepare-workdir 
      # The config-generator chart needs access to the config manifests
      # Copy config manifests into config-generator chart
      - uses: copy
        config:
          inPath: "${% vars.path_src %}/config"
          outPath: "${% vars.path_src %}/charts/config-generator/config/platform"
      - uses: copy
        config:
          inPath: "${% vars.path_src %}/applications/argocd/config"
          outPath: "${% vars.path_src %}/charts/config-generator/config/application"
      # Render the config files from templates
      - uses: helm-template
        config:
          releaseName: config-generator
          path: "${% vars.path_src %}/charts/config-generator"
          outLayout: flat
          outPath: /tmp/values.yaml
          setValues:
            - key: envName
              value: management
            - key: envType
              value: management
            - key: appName
              value: argocd
      - uses: helm-template
        config:
          releaseName: argocd
          namespace: argocd
          buildDependencies: true
          includeCRDs: true
          path: "${% vars.path_src %}/applications/argocd"
          outPath: "${% vars.path_out %}/deploy/argocd"
          valuesFiles:
          - /tmp/values.yaml
      - task:
          name: push-manifests
        as: promotion
        vars:
        - name: asPR
          value: "true"
        - name: targetBranch
          value: env/management/argocd
      - uses: argocd-update
        config:
          apps:
          - name: management-argocd
            sources:
            - repoURL: "${% vars.gitRepo %}"
              desiredRevision: "${% outputs.promotion.commit %}"
---
# Source: application-generator/templates/stage.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: management-kargo-config
  namespace: homelab-management
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-config
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/syoder89-homelab/homelab-management
      - name: targetBranch
        value: env/management/kargo-config
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
      - task:
          name: prepare-workdir 
      # The config-generator chart needs access to the config manifests
      # Copy config manifests into config-generator chart
      - uses: copy
        config:
          inPath: "${% vars.path_src %}/config"
          outPath: "${% vars.path_src %}/charts/config-generator/config/platform"
      - uses: copy
        config:
          inPath: "${% vars.path_src %}/applications/kargo-config/config"
          outPath: "${% vars.path_src %}/charts/config-generator/config/application"
      # Render the config files from templates
      - uses: helm-template
        config:
          releaseName: config-generator
          path: "${% vars.path_src %}/charts/config-generator"
          outLayout: flat
          outPath: /tmp/values.yaml
          setValues:
            - key: envName
              value: management
            - key: envType
              value: management
            - key: appName
              value: kargo-config
      - uses: helm-template
        config:
          releaseName: kargo-config
          namespace: homelab-management
          buildDependencies: true
          includeCRDs: true
          path: "${% vars.path_src %}/applications/kargo-config"
          outPath: "${% vars.path_out %}/deploy/kargo-config"
          valuesFiles:
          - /tmp/values.yaml
      - task:
          name: push-manifests
        as: promotion
        vars:
        - name: asPR
          value: "true"
        - name: targetBranch
          value: env/management/kargo-config
      - uses: argocd-update
        config:
          apps:
          - name: management-kargo-config
            sources:
            - repoURL: "${% vars.gitRepo %}"
              desiredRevision: "${% outputs.promotion.commit %}"
---
# Source: application-generator/templates/stage.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: management-kargo
  namespace: homelab-management
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/syoder89-homelab/homelab-management
      - name: targetBranch
        value: env/management/kargo
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
      - task:
          name: prepare-workdir 
      # The config-generator chart needs access to the config manifests
      # Copy config manifests into config-generator chart
      - uses: copy
        config:
          inPath: "${% vars.path_src %}/config"
          outPath: "${% vars.path_src %}/charts/config-generator/config/platform"
      - uses: copy
        config:
          inPath: "${% vars.path_src %}/applications/kargo/config"
          outPath: "${% vars.path_src %}/charts/config-generator/config/application"
      # Render the config files from templates
      - uses: helm-template
        config:
          releaseName: config-generator
          path: "${% vars.path_src %}/charts/config-generator"
          outLayout: flat
          outPath: /tmp/values.yaml
          setValues:
            - key: envName
              value: management
            - key: envType
              value: management
            - key: appName
              value: kargo
      - uses: helm-template
        config:
          releaseName: kargo
          namespace: kargo
          buildDependencies: true
          includeCRDs: true
          path: "${% vars.path_src %}/applications/kargo"
          outPath: "${% vars.path_out %}/deploy/kargo"
          valuesFiles:
          - /tmp/values.yaml
      - task:
          name: push-manifests
        as: promotion
        vars:
        - name: asPR
          value: "true"
        - name: targetBranch
          value: env/management/kargo
      - uses: argocd-update
        config:
          apps:
          - name: management-kargo
            sources:
            - repoURL: "${% vars.gitRepo %}"
              desiredRevision: "${% outputs.promotion.commit %}"
