---
# Source: application-generator/templates/warehouse.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: argocd
  namespace: homelab-management
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 10
      strictSemvers: true
      repoURL: https://github.com/syoder89-homelab/homelab-management.git
      includePaths:
      - applications/argocd
---
# Source: application-generator/templates/warehouse.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-config
  namespace: homelab-management
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 10
      strictSemvers: true
      repoURL: https://github.com/syoder89-homelab/homelab-management.git
      includePaths:
      - applications/kargo-config
---
# Source: application-generator/templates/warehouse.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo
  namespace: homelab-management
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 10
      strictSemvers: true
      repoURL: https://github.com/syoder89-homelab/homelab-management.git
      includePaths:
      - applications/kargo
